### ISSUE TITLE
Dropbox upload doesn't seem to be working

### ISSUE THREAD

**Issue by johenkel** [nibogd/ingress-ice#101]
Using ICE v4.4.1 on an Ubuntu 16.04 system,
the dropbox upload does not seem to be working entirely. The files are being uploaded but they are corrupted. They cannot be opened using any image viewer, also web dropbox cannot open them as well.
Do you have any idea on what could be done ?

Also -not sure if I should open another issue-  , is there a way to enable regular google authorization ?
The two-step doesn't work, it doesn't trigger getting a SMS for a PIN, nor does it accept any printed codes from my google account. 
Using the cookie data will get it working though.

Thanks

**Comment by c2nprds** [comment]
It certainly is broken.
I will investigate a little.

**Comment by c2nprds** [comment]
@johenkel
the problem will be fixed in #102 PR.

**Comment by johenkel** [comment]
Thank you @c2nprds  ! 
It is working now - very fast fix ! :)

**Comment by c2nprds** [comment]
:+1:
