### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by htomasz** [nibogd/ingress-ice#105]
I get all the times login problem

13.02.2017 07:40:12: Something went wrong. Please, sign in to Google via your browser and restart ICE. Don't worry, your Ingress account will not be affected.
Try it but no luck.
Also try using with coockie, also nothing 
Im able to login to account in google and in ingress

System: Fedora 25
Browser: Chrome/Firefox

FIXED add --ignore-ssl-errors=true

Can be closed

**Comment by NanoExplorer** [comment]
I'm having a similar problem. Trying to log in with cookies results in "ICE crashed. Reason: Cookies are obsolete. Update your config file :("
Trying to sign in with credentials results in the same problem above. "something went wrong..."
System: Linux Mint 17
Browsers tried: chrome and firefox.

I tried adding --ignore-ssl-errors=true, and it reported that '--' is not a valid option.

**Comment by nibogd** [comment]
@htomasz thanks for that fix, I'll probably add it as a setting.
@NanoExplorer I think you should add that as a PhantomJS option. You can do that by replacing each `$PHANTOMJS "$SCRIPT_HOME/ice/ice.js" $ARGS` with `$PHANTOMJS --ignore-ssl-errors=true "$SCRIPT_HOME/ice/ice.js" $ARGS` in `ingress-ice.sh`.

**Comment by alesanmed** [comment]
I've tried that fix but I'm still having the same issue, still getting the message "Something went wrong. Please, sign in to Google via your browser and restart ICE. Don't worry, your Ingress account will not be affected."

I've tried with google credentianls and with cookies, no luck. Any advice?

**Comment by nibogd** [comment]
@alesanmed, sorry, have no idea.
