### ISSUE TITLE
Can't complete two-step verify

### ISSUE THREAD

**Issue by magicboy110** [nibogd/ingress-ice#106]
When My IP changed ,I enter my security email to pass the  Google two-step verify in Chrome browser.
But in ingress-ice, I entered my  security email and got an error.
What's the two-step Code? Where can I get it ?

**Comment by MTRNord** [comment]
Probably it is a captcha. Try unblock via https://accounts.google.com/displayunlockcaptcha it should  theoretically it should Show The captcha on another device. Means first open The Link. Than do what is told you on it. For me it worked.

**Comment by nibogd** [comment]
@MTRNord thanks for that!
@magicboy110 what do you mean by 'security email'? If you use two-step authentication, just get the code for ingress-ice as you usually do for browser logins.
