### ISSUE TITLE
Change IITC plugin URL

### ISSUE THREAD

**Issue by Dennixx** [nibogd/ingress-ice#108]
In the code the 'old' URL for IITC is still used (https://secure.jonatkins.com/iitc/release/total-conversion-build.user.js), however it should probably be retrieved from the new URL (https://static.iitc.me/build/release/total-conversion-build.user.js)

Earlier today the old URL was unreachable causing ICE to use stock intel.

**Comment by kostamuspoika** [comment]
Seems to be ok for me.

**Comment by nibogd** [comment]
Done, thank you.
