### ISSUE TITLE
Dancing portals.

### ISSUE THREAD

**Issue by mxxcon** [nibogd/ingress-ice#11]
This is what happens in my screenshots. Portals randomly change which one is on top with each screenshot. Regular browser screenshot doesn't do that.
I'm running phantomjs.exe 2.0
![output_r7y5ct](https://cloud.githubusercontent.com/assets/847140/6702601/795fae34-cd04-11e4-9d9f-db7bb567fb92.gif)

**Comment by nibogd** [comment]
That's because phantomJS renders it again  and chooses portal's layer randomly. I can't fix that :(. Is this critical for you?

**Comment by mxxcon** [comment]
It creates needless visual noise. Distracts from the subject that I'm screenshotting. Harder to spot the actual change. And resulting videos require higher bitrate.

**Comment by nibogd** [comment]
Sorry, i can't fix that :(
Maybe you should try slimmerJS instead of phantom...
