### ISSUE TITLE
IITC cannot be downloded

### ISSUE THREAD

**Issue by RomanIsko** [nibogd/ingress-ice#114]
Hi @nibogd 
I'm asking you to release new version because of IITC plugin is no longer available at _https://secure.jonatkins.com/iitc/release/plugins/link-show-direction.user.js_

Now it's needed to use this URL _https://static.iitc.me/build/release/plugins/link-show-direction.user.js_ for IITC download during making screenshots. This issue is fixed in sources in pull request #110 from **mxxcon/patch-1**

Please just release new Ice version with fix so users can use IITC. 

Thanks

**Comment by nibogd** [comment]
Done!
