### ISSUE TITLE
Some strange error

### ISSUE THREAD

**Issue by htomasz** [nibogd/ingress-ice#118]
06.04.2018 18:35:06: Screen saved
./ingress-ice.sh: line 26: 26073 Killed                  $PHANTOMJS $PHANTOMJS_FLAGS "$SCRIPT_HOME/ice/ice.js" $ARGS
[n0ut@changeme ingress-ice]$

**Comment by htomasz** [comment]
Fixed. Oout OF Memory :D

**Comment by nibogd** [comment]
Oh, I read the email and wanted to finally look into the issues. Still have not much time, but closed one more because you've reminded me of them. Thanks :sweat_smile:
