### ISSUE TITLE
Save google auth cookies

### ISSUE THREAD

**Issue by ch** [nibogd/ingress-ice#12]
Can you save google cookies for restore session at restart?

**Comment by nibogd** [comment]
It's possible, but why do you need it? The only benefit from it i can imagine is start speed. But the cookies could only be stored in plaintext in filesystem. It is a security hole. I don't think this is a feature you need...

**Comment by ch** [comment]
2х факторная авторизация задолбало СМС вводить постоянно при отладке

**Comment by nibogd** [comment]
А, в таком случае рекомендую сделать отдельный аккаунт, и не забанят основной :blush: Просто куки в тексте - это реально дыра, а аккаунт завести несложно новый

**Comment by ch** [comment]
я уже сделал. чтобы куки в файл сохранялись, с него и читаю.
но всё равно спасибо :)

2015-03-24 10:18 GMT+02:00 Nikita-kun <notifications@github.com>:

**Comment by nibogd** [comment]
Незачто ) Тогда, закрываю issue
