### ISSUE TITLE
TypeError: null is not an object

### ISSUE THREAD

**Issue by mxxcon** [nibogd/ingress-ice#14]
Current just-checked out version.
I set the following parameters:
```
set MINLEVEL=8
set MAXLEVEL=8
set DELAY=120
set WIDTH=1920
set HEIGHT=1080
```
I get the following error:
```
     _____ )   ___      _____)
    (, /  (__/_____)  /
      /     /         )__
  ___/__   /        /
(__ /     (______) (_____)  v2.0.3 (https://github.com/nibogd/ingress-ice)

If something doesn't work or if you want to submit a feature request, visit http
s://github.com/nibogd/ingress-ice/issues
Connecting...
Logging in...
URI is now https://accounts.google.com/SecondFactor... .
Verifying login...
Using two-step verification, please enter your code:
615556
TypeError: null is not an object (evaluating 'document.querySelector('#comm').st
yle')

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():9
TypeError: null is not an object (evaluating 'minAvailable.id')

  ice.js:64 in setminmax
  ice.js:206
```

**Comment by mxxcon** [comment]
If I set 
```
set MINLEVEL=1
set MAXLEVEL=8
```
Then I get the following error:
```
TypeError: null is not an object (evaluating 'document.querySelector('#comm').st
yle')

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():9
TypeError: null is not an object (evaluating 'document.querySelector("#filters_c
ontainer").style')

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
```

**Comment by nibogd** [comment]
The level selector repeats user actions (clicking on level selectors in interface), and if interface didn't load, it crashes :sweat: 
Please try setting longer delay so that the page loads first

**Comment by mxxcon** [comment]
I increased timeout to 240 and it seems to work.
If I set min max portals to 8, phantomjs crashes. min-1, max-8 works. :confused:

**Comment by nibogd** [comment]
A bit strange... Maybe you should set only minimal level?.. So that less loading

**Comment by mxxcon** [comment]
that's the thing..when I set it to show only lvl8 portals, it crashes. but lvl1-8 works.

**Comment by nibogd** [comment]
Sorry, it "works on my machine" :sweat:  so i can't fix it :(

**Comment by mxxcon** [comment]
This is the center https://www.ingress.com/intel?ll=40.754636,-73.93301&z=13
Do you use linux/mac/win?

**Comment by nibogd** [comment]
Linux, but it should have same bugs on all platforms :D

**Comment by SniperRus** [comment]
if I use cuatom portal level - the map is blank :(

**Comment by nibogd** [comment]
Huh? That works for me, but very laggy. Maybe i should delete this feature...
Thanks for bug report. I'll look into it.

**Comment by nibogd** [comment]
@SniperRus , please try setting a higher delay, that should help...

**Comment by nibogd** [comment]
@SniperRus , i've edited the script, please, try again, hope that helps…

**Comment by SniperRus** [comment]
with more z= and timeout in draw the map, but with level's fliter box
try to experiment again with different parameters
when i choice make only 2 screenshot - it make more that 2...
http://shot.qip.ru/00Hsp0-5I0Rrenhy/

**Comment by nibogd** [comment]
@SniperRus , i fixed the counter, thanks for report :)
I'll try to do something about levels a bit later, maybe tomorrow... Actually i don't know what to do

**Comment by SniperRus** [comment]
maybe you can lookup into iitc plugin how they work with selectable portal level layers? and do similar way? or for stock intel it impossible to do the same way?

**Comment by nibogd** [comment]
Bug #16 better represents the error, I'm closing this thread as they are about the same.

**Comment by nibogd** [comment]
@SniperRus sorry, didn't see your message. Thanks for a suggestion, but AFAIK they fully replace stock intel map, so the way is different. In the stock map everything is obfuscated, so i can't do it via js

**Comment by SniperRus** [comment]
@nibogd may be you can look in this git, how they use portal level selection - https://github.com/leoxiong/ingress-intel-timelapse

**Comment by nibogd** [comment]
@SniperRus Thank you :) That's the same way that i do. Mine should work from last release :)
