### ISSUE TITLE
First captured screen is not saved

### ISSUE THREAD

**Issue by RomanIsko** [nibogd/ingress-ice#15]
**Environment:** Ubuntu 14.04.

**steps:**
1. configure to capture e.g. 5 screenshots in your area.
2. start with sh.script.
3. wait for screenshots to be captured.
4. check if first screenshot is saved (compare date in file name)

**Actual:**
Connecting...
Logging in...
Screen #1/5 captured
Custom highest portal level may work bad with low delay. If it doesn't work well, set a higher delay.
Screen #2/5 captured
Custom highest portal level may work bad with low delay. If it doesn't work well, set a higher delay.
2015-04-30--13-06-55: screen saved
Screen #3/5 captured
Custom highest portal level may work bad with low delay. If it doesn't work well, set a higher delay.
2015-04-30--13-07-55: screen saved
Screen #4/5 captured
Custom highest portal level may work bad with low delay. If it doesn't work well, set a higher delay.
2015-04-30--13-08-56: screen saved
........

**Expected:**
Connecting...
Logging in...
Screen #1/5 captured
Custom highest portal level may work bad with low delay. If it doesn't work well, set a higher delay.
2015-04-30--13-05-55: screen saved
Screen #2/5 captured
Custom highest portal level may work bad with low delay. If it doesn't work well, set a higher delay.
2015-04-30--13-06-55: screen saved
Screen #3/5 captured
.........

**Comment by nibogd** [comment]
Thank you for the report, I'll fix it now. It's a silly mistake, the counter starts before the screenshooter :sweat:

**Comment by nibogd** [comment]
Fixed, please update your ICE :)
