### ISSUE TITLE
Screen is captured without setting MINLEVEL

### ISSUE THREAD

**Issue by RomanIsko** [nibogd/ingress-ice#16]
Environment: Ubuntu 14.04

steps:
- set MINLEVEL='5' and set MAXLEVEL='8' in start.sh
- run ./start.sh
- wait for the third screenshot
- check if filter 'Portals' is applied 

Actual: sometimes the value MINLEVEL is not applied for area on screenshot
Expected: all screenshots are captured 
according to settings 

Note: screenshots  is attached 
![ice-2015-04-30--13-24-23](https://cloud.githubusercontent.com/assets/4456572/7410999/87876c22-ef3c-11e4-8f6a-5e328eda62fc.png)

![ice-2015-04-30--13-25-23](https://cloud.githubusercontent.com/assets/4456572/7410985/6ec14960-ef3c-11e4-91d8-718825515edf.png)

**Comment by nibogd** [comment]
We discussed it in #14 , thanks for the report. As for now, the only way not to get this problem is to set higher delay, the bigger the better.

**Comment by mxxcon** [comment]
I had delay of 300(5minutes) and still out of 114 screenshots only 1st one had correct minlevel. Does it mean it takes longer than 5min to completely load intel?

**Comment by nibogd** [comment]
@mxxcon , yes. We first load the site and then we load portals with needed level. And we can't change that :sweat: 
If your region is not too active, i think 10 minutes will be enough...

**Comment by mxxcon** [comment]
I play in NYC, it's very active. :smile: I'm trying to document ops like this https://lh3.googleusercontent.com/-pcRbQ1BFPWQ/VWCaxe4JgxI/AAAAAAAAZNk/_YMqrr8nZiI/w760-h428-no/ice-2015-05-22--21-28-29-ANIMATION.gif

**Comment by nibogd** [comment]
@mxxcon Lucky :) My city is usually half-blue and half-green, divided by the forest. I live in blue part and wait for enlights to come and destroy everything…

**Comment by mxxcon** [comment]
I just run another series of screenshots with 10 minutes timeout. Still only 1st screenshot respected 8/8, everything else was 2/8 with zoom level 14.

**Comment by nibogd** [comment]
@mxxcon i found out the reason: it's a phantomJS's lag :(
I'm now rebuilding ice so it will not reload page each time, but the page will reload itself. Delay will have to be higher than 4 minutes, but portal level selector will be fixed.

**Comment by mxxcon** [comment]
:+1:

**Comment by nibogd** [comment]
Fixed!

**Comment by mxxcon** [comment]
just did a mini-test and indeed, it's working as expected :+1: (other than having to install 64bit phantomjs bin)
