### ISSUE TITLE
Nothing happen after Logging in...

### ISSUE THREAD

**Issue by stunna** [nibogd/ingress-ice#17]
Hi 

Thx for you great work. Version 1.3.1 is working and I tried to run the new 2.0.2 under windows and linux but it does not go further than 

"Logging in..." 

I tried to fill the variables manual but it did not help, may I use it in a wrong way but I do not think so.

sincerely

**Comment by nibogd** [comment]
Hello
Glad you like this tool :)

What is your delay in settings? You should wait at least twice that time (sorry, this is the way it works :sweat: ).

**Comment by stunna** [comment]
Hey, cool short reaction :)

DELAY was on 120, i changed it to 30, now I can see a result.

2015-05-27--23-54-32: screen saved.

Thank you.

ps: I am just wondering wher the comm logs are, in Version 1.3.1 the come to the Console.log output

**Comment by nibogd** [comment]
Comm logs? This script doesn't parse the chat, cuz niantic may ban for that
