### ISSUE TITLE
Display only some elements

### ISSUE THREAD

**Issue by mxxcon** [nibogd/ingress-ice#20]
It would be nice to be able to turn on/off displaying of links, fields for each faction.
For example, I want to see only EP6's, not RP6 and not links/fields. Or I only want to see RES fields w/o even links to make screenshots a bit cleaner.

**Comment by nibogd** [comment]
Are you using IITC with ICE? If not, it is impossible. If yes, i'll look into it.

**Comment by mxxcon** [comment]
So far w/o iitc.

**Comment by nibogd** [comment]
If so, that is actually impossible.

**Comment by mxxcon** [comment]
I'm fine to use iitc if that's a requirement for such functionality.

**Comment by nibogd** [comment]
I'll try to implement this later :)

сб, 20 июня 2015 г. в 0:17, mxxcon <notifications@github.com>:

**Comment by nibogd** [comment]
Sorry for waiting so long :(
Now it's done. Usage is a bit tricky (i didn't want to make the setup too complicated), you can learn it [here](https://github.com/nibogd/ingress-ice/wiki/Remove-features).

By the way, thanks to this issue, i've discovered a little GitHub vulnerability :smile:
