### ISSUE TITLE
Take first screenshot as soon as app starts

### ISSUE THREAD

**Issue by mxxcon** [nibogd/ingress-ice#21]
I screenshot at 1920x1080, but my monitor is of different resolution so it's not an exact match.
If I set interval to 10 minutes, presently after starting ingress-ice I have to wait 10 minutes only to see that url is not perfect. :smile: 
So now I have to run it with 1 minute interval, check screenshot, and then reconfigure, check again and then set the proper interval.
Would be nice if it took the 1st screenshot as soon as it starts.

**Comment by nibogd** [comment]
I can't do this because Intel map may not load within 5 minutes (sometimes it's like this) :sob:

**Comment by adostes** [comment]
The goal of the first screenshot is not to see the portal info but to see if the screenshots are correctly framed in, I think it's acceptable that the first screenshot doesn't have any information.

**Comment by nibogd** [comment]
Done.
