### ISSUE TITLE
Multiple configuration files

### ISSUE THREAD

**Issue by h3tz** [nibogd/ingress-ice#22]
In case i want to start in parallel up to x instances i want to pass the interface the configration file as argument.

**Comment by nibogd** [comment]
Do you use linux? If yes, try 
```
./ingress-ice -i config1&./ingress-ice -i config2
```
Or just run them in separate consoles

**Comment by h3tz** [comment]
i would like to use windows.

2015-06-23 11:43 GMT+02:00 Nikita-kun <notifications@github.com>:

**Comment by nibogd** [comment]
If so, you can edit `ingress-ice.cmd` file. Copy it multiple times and change the
```
set FILE=%APPDATA%\.ingress_ice
```
on 11th line to
`set FILE=%APPDATA%\.ingress_ice-1`, `set FILE=%APPDATA%\.ingress_ice-2`…

Or you can wait untill i make a command line key for windows, but i think it would be less convinient for you. (You would have to start it from console, not double-clicking files)

**Comment by h3tz** [comment]
Thanks for your help. I really would like to prepare having a commandline
interface to handle the arguments : intel link, level min, level max.

Lets talk about in plus hetzandreas@gmail.com

2015-06-23 13:04 GMT+02:00 Nikita-kun <notifications@github.com>:

**Comment by nibogd** [comment]
You can use command-line arguments with phantomJS and no config files, as written [here](https://github.com/nibogd/ingress-ice/wiki/Config-file-format).
```
./phantomjs ice.js $VERSION $EMAIL $PASSWD $LINK $MIN_LEVEL $MAX_LEVEL $DELAY $WIDTH $HEIGHT $FOLDER $NUMBER $IITC $TIMESTAMP
```
which will look like 
```
./phantomjs ice.js 1 some-email "This$is&my*passwd" "https://www.ingress.com/intel?ll=52.98348,5.071092&z=3" 8 8 300 4096 2160 /home/link/ice/ 0 0 0
```
