### ISSUE TITLE
you ca use ffmpevg to create a movie (no issue)

### ISSUE THREAD

**Issue by 0x25** [nibogd/ingress-ice#24]
hello

maby you can add some ffmpeg command line in your readme . 
because I think the purpose of tacking screenshot is to create movie

best regards
thanks for sharing your code, greate job.

**Comment by nibogd** [comment]
Hello,

thank you for suggestion.
I personally use `mencoder`, something like `mencoder mf://*.png -mf w=1920:h=1080:fps=12.5:type=png -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell -oac copy -o output.avi` to create avi

**Comment by nibogd** [comment]
Added to readme, thanks!
