### ISSUE TITLE
Captcha on login?

### ISSUE THREAD

**Issue by fivepointseven** [nibogd/ingress-ice#28]
![screen shot 2015-07-17 at 02 30 56](https://cloud.githubusercontent.com/assets/8418866/8737548/e37f4884-2c2b-11e5-9e4e-1a9a9ad4f274.png)
This is what I get trying to authenticate with Ice. How can this be fixed?

**Comment by nibogd** [comment]
Seems like it's something related to #29 . Ice worked a day ago, maybe bot guard was enabled. Investigating right now.

**Comment by nibogd** [comment]
Please try to use cookie authentication untill login/password will work. If you don't know how, send me your browser and operating system versions and i'll tell you how.

**Comment by nibogd** [comment]
Or just try again after logging in through incognito mode of your browser, google should end their suspicions. Sorry for inconvenience.

**Comment by fivepointseven** [comment]
It worked once and I had the same issue as described in #29 - Sign In button screenshot. Then it started to show captcha, I tried to log in with browser, clicked "Yes, it was me" on Google's "Suspicious login prevented" bud captcha kept going. 
How do I use cookie authentication? I'm running Safari/Chome on OS X 10.11

**Comment by nibogd** [comment]
To use cookies:
 1. Open console in the folder with ice, run ./ingress-ice -r
 2. Log in to ingress in your Chrome
 3. Press the 
![image](https://cloud.githubusercontent.com/assets/2771136/8744852/33293460-2c83-11e5-8e97-8bf5a6f6903a.png)
 sign
 4. Press "Show cookies" or something like this
 5. Open the `www.ingress.com` submenu (
![image](https://cloud.githubusercontent.com/assets/2771136/8744887/62081738-2c83-11e5-96e3-c42e206b9517.png))
 6. Open `Cookie files`
 7. Click on 
![image](https://cloud.githubusercontent.com/assets/2771136/8744918/921b5944-2c83-11e5-9953-b08c5f028956.png)
 8. Copy it's contents (something like 
![image](https://cloud.githubusercontent.com/assets/2771136/8744931/b6aeef6e-2c83-11e5-8db0-48a843d13c0c.png))
 9. Return to your console, insert the area link and choose `yes` in the next dialog
 10. Paste (usually <kbd>Shift</kbd> + <kbd>Insert</kbd>, don't know, how on Mac) your SACSID
 11. In browser, click 
![image](https://cloud.githubusercontent.com/assets/2771136/8744981/0ba7ff56-2c84-11e5-8885-3da741b87057.png)
 12. Again, copy it's contents and paste into the next dialog
 13. Next steps as usual

Again, sorry for inconvenience.

**Comment by fivepointseven** [comment]
Thanks, I'll try. Another question here however is the whole point why I started using Ice. I used basic Phantom screenshotter that had a cookie authentication. The problems I ran into were (a) cookies expiring and resulting in "Sign In screen" which needed manual cookie update and (b) - short time after screenshotting Intel started to throw a white screen with "Sorry, but your computer and network appears to be sending automated requests". Won't this happen with Ice if using cookie authentication?

**Comment by nibogd** [comment]
The first is inevitable, cookies tend to stale, but the second shouldn't happen — ice acts as a usual browser without reloading ingress.com. It only clicks when `Human presence not detected` text appears.

**Comment by fivepointseven** [comment]
![screen shot 2015-07-17 at 13 34 14](https://cloud.githubusercontent.com/assets/8418866/8745436/923fdb70-2c88-11e5-9feb-d253ec5b1ba9.png)
And this is what I get now when trying password authentication on IP where Ice is running. From my home computer this account logs in lust fine

**Comment by nibogd** [comment]
Hmm... Did you get banned for using ice or it happened before? I think there is no way other than to wait to be able to log in successfully. By the way, I've been using ice for 20 days without breaks and it was fine — no any suspicions from Google.

**Comment by fivepointseven** [comment]
I guess I just made Google suspicious with old version of Ice trying to get through their new login form. I'll keep you posted if something will go wrong with this account

**Comment by nibogd** [comment]
Ask me if you need help :)
