### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by pleasantone** [nibogd/ingress-ice#29]
Hi, do we think that as of 3.1.0, ingress-ice should be working? I just tried it (with my own phantomjs) under debian linux, and I never get past the sign in form, using either standard, or cookie, authentication. My screenshot is the "Welcome to Ingress ... sign in / learn more" dialog.
Console dialog is: v3.1.0
If you need help or want a new feature, visit https://github.com/nibogd/ingress-ice/issues
16.07.2015 18:08:47: Will start screenshooting in 120 seconds...
16.07.2015 18:08:47: The first screenshot may not contain all portals, it is intended for you to check framing.
16.07.2015 18:08:49: Screen saved

Again, I've tried it with both standard and cookie authentication.

**Comment by nibogd** [comment]
Sorry, ice worked a day ago, maybe bot guard was turned on. Investigating right now...

**Comment by pleasantone** [comment]
Just got it working in password mode, https doesn't work at all, http ok. Cookie mode is nonfunctional. Will debug further tomorrow.

**Comment by nibogd** [comment]
Cookie mode works for me. Screenshot taken a minute ago:
![ice-2015-07-17--10-53-37](https://cloud.githubusercontent.com/assets/2771136/8742070/fedf785e-2c69-11e5-86d8-423e6d1e54a9.png)

**Comment by nibogd** [comment]
Are you sure you use needed cookies? The first should be a long one (738 symbols mine), and the second is 38 letters

**Comment by nibogd** [comment]
https://www.ingress.com/intel?ll=53.228304,50.199752&z=16 here is my link; it's https. Maybe some changes in google in the USA?..

**Comment by pleasantone** [comment]
It's 0:00 here, will re-check in the AM.
Need to figure out how to retrieve cookies in phantomjs. I think it would be nice if we could login with user/password once, then switch to cookies automatically to avoid new signon alerts from Google.

**Comment by pleasantone** [comment]
Yes, copied properly from chrome.

**Comment by nibogd** [comment]
Hmm... Strange...
I don't want to store cookies in text by default, but maybe that is the best solution... Cookies tend to stale

**Comment by nibogd** [comment]
Tested just now; both cookies and login/password work for me.

Please, try running testing version (https://github.com/nibogd/ingress-ice/tree/testing), it will produce screenshots for debugging and print your cookies to console if logging in using login and password.

**Comment by pleasantone** [comment]
Yes, it’s now working for me, very strange. I copied the cookie strings out of the testing version, they matched the ones from my browser.

FWIW, I am now using ice.js running with phantomjs with the cookies file enabled. I think it’s fairly easy to change the code to switch to cookie based logins automatically once the user authenticates once, so that we don’t need to store username/passwords.

**Comment by nibogd** [comment]
Nice :) Thank you for using ice!
