### ISSUE TITLE
IITC stopped working

### ISSUE THREAD

**Issue by fivepointseven** [nibogd/ingress-ice#30]
Hi. For some reason when I try to take screenshot with IITC enabled, it results in screenshots like this:
![iitcfail](https://cloud.githubusercontent.com/assets/8418866/8894231/747fda78-33b7-11e5-9ca9-9837e8e2a149.jpg)
What may be the reason of this?

**Comment by nibogd** [comment]
Thank you for the report, i'll test it now. There is a single link on your map, maybe it haven't loaded yet?

**Comment by nibogd** [comment]
![ice-2015-07-26--18-08-19](https://cloud.githubusercontent.com/assets/2771136/8894279/f05fef60-33b8-11e5-8a0c-309d8cb5d48c.png)

Works for me; tested just now. Is that the first screenshot?

**Comment by fivepointseven** [comment]
@nibogd This single link in fact does not exist. One time I had some blue links loaded in the sea.
Yes, it's a first screenshot, but IITC console says that loading is fully completed.

**Comment by nibogd** [comment]
@fivepointseven strange... IITC console? It's messages are not always right, maybe wait for the second screenshot? First screenshot is usually incomplete

**Comment by fivepointseven** [comment]
![iitcfail2](https://cloud.githubusercontent.com/assets/8418866/8894324/8976eb76-33ba-11e5-8262-a604441895e4.jpg)
This is the second screenshot with timeout increased just in case.
Console final report:
CONSOLE: finished requesting data! (took 6.659 seconds to complete)
CONSOLE: starting map refresh in 300 seconds

**Comment by nibogd** [comment]
That's strange, your internet connection must be really slow... Does it work without IITC? Which version of ice?

**Comment by nibogd** [comment]
And what about a regular browser? How much does i take for all links and fields to load?

**Comment by fivepointseven** [comment]
3.1.0
It works with stock intel, and internet speed is not the case - testing on Digital Ocean's server.
And IITC works in regular browser.

**Comment by nibogd** [comment]
Would you mind testing it on that system on which you use regular IITC? Sorry, i have no clue why it is so :(

**Comment by fivepointseven** [comment]
On my local system Intel responds with 403 because of sanctions and if using VPN Intel only works via browser for some reason.
Well, thanks anyway. I'll keep you posted if I'll figure out what's wrong.

**Comment by nibogd** [comment]
Sorry, i can't help now :( Maybe i'll look into it a bit later, but i don't have any idea what may be wrong...

**Comment by fivepointseven** [comment]
I fixed it.
Warning to everyone using Ice - don't try to add custom user agent if using IITC.
I removed the `page.settings.userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36';` which I added yesterday and everything worked again like a charm.
But I have no idea, how's that connected -_-

**Comment by nibogd** [comment]
Thank you! Glad you've figured out the reason  :)
It may be that IITC adds custom hacks depending on UA string, which didn't work for phantom
