### ISSUE TITLE
No background when using IITC

### ISSUE THREAD

**Issue by soend** [nibogd/ingress-ice#32]
Has anybody seen this strange thing before:https://www.dropbox.com/s/jelsecxbpzoin6e/812320494_16294_15039771292486162114.jpg?dl=0

I have no clue why this could be like that...

**Comment by nibogd** [comment]
What is your OS and phantomJS version? Have you modified the script?

**Comment by soend** [comment]
Linux soojendi 3.13.0-46-generic #75-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
PhantomJS version 1.9.0

I specially made fresh checkout from git to test this, so the script is not modified.

**Comment by nibogd** [comment]
@soend please try a higher version of PhantomJS, at least 1.9.3. Either delete your system PhantomJS or edit the ingress-ice script:
change
```

if [ "$OSTYPE" = "darwin"* ]; then
    PHANTOMJS="./phantomjs-osx"
else
    if (command -v phantomjs >/dev/null)
    then
        PHANTOMJS='phantomjs'
    else
        PHANTOMJS="./phantomjs"
    fi
fi
```
into
```
PHANTOMJS="./phantomjs"
```

**Comment by nibogd** [comment]
Or just update the script, I've changed ingress-ice script so that system Phantom is never used

**Comment by soend** [comment]
Afther updating the script i get this:
./ingress-ice: 490: ./ingress-ice: ./phantomjs: not found

**Comment by nibogd** [comment]
Oh, sorry, i need to add a 64-bit version of PhantomJS
Please, wait 5 minutes

**Comment by nibogd** [comment]
Please, update again now. Sorry for such inconvenience :(

**Comment by soend** [comment]
Thanks, now it works.

**Comment by nibogd** [comment]
:)
