### ISSUE TITLE
Convert to Bash?

### ISSUE THREAD

**Issue by pheanex** [nibogd/ingress-ice#37]
Is there a specific reason to use /bin/sh over explicit /bin/bash ?
Doesn't the standard-shell cause more problems (since its different on more platform?)

**Comment by nibogd** [comment]
sh is more cross-platform, e. g. in FreeBSD there is no bash in default setup. So i prefer sh here.

**Comment by pheanex** [comment]
/bin/sh is actually just the default shell iirc
So its just a symlink to the actually used shell like /bin/bash on debian (whats it on mac/freebsd and co btw?)
=> I thought we could gain stability by explicitly using a certain shell instead of "the standard one on a specific system"?
