### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by pheanex** [nibogd/ingress-ice#40]
When taking a screenshot every 2 minutes, phantomjs is consuming 100%CPU for about 90 seconds after rendering a screenshot (1 mailaddress username https://www.ingress.com/intel?ll=50.940974,6.98158&z=13 1 8 120 1920 1080 ./ 0 0 1). Is that to be expected or is this a bug?

**Comment by nibogd** [comment]
That's all PhantomJS is about :( It's laggy sometimes and consumes alot of CPU and RAM. I cannot do anything about this, sorry.

**Comment by pheanex** [comment]
I know this also might be because ingress.com/intel is really slow and sux, and we got to do the human presence, but i ran the docker container overnight and after a while it went completely 100%cpu.(Do you have similar problems?) Is there nothing we can do about this, like putting phantomjs to sleep while waiting for the next screenshot to take or similar? ideas?

**Comment by nibogd** [comment]
Hmm... PhantomJS, QtWebKit, Ingress Intel (and my algorythms) — they all
are not perfect :(
I have no idea how to do that. We could run phantom every N minutes using
cron, but it needs some time to load and won't work on windows...

пн, 31 авг. 2015 г. в 11:29, PHeanEX <notifications@github.com>:
