### ISSUE TITLE
Set the user-agent?

### ISSUE THREAD

**Issue by c2nprds** [nibogd/ingress-ice#42]
Phantomjs default `user-agent` looks like:
`Mozilla/5.0 (Macintosh; PPC Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34`

It is recommended to use for safety's sake, the common browser user agent.

https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Tools/QtTestBrowser/useragentlist.txt
http://phantomjs.org/api/webpage/property/settings.html

**Comment by nibogd** [comment]
Nice idea, but some users reported that it doesn't work with custom
user-agent :(

**Comment by nibogd** [comment]
Huh, that works. Will change UA to Win7 (one of the most common — for the sake of conspiracy) in v4.0.0

**Comment by nibogd** [comment]
Thank you!

**Comment by nibogd** [comment]
Removed due to #47 (bug in some configurations) :(
Idea is great, but phantom is laggy...
