### ISSUE TITLE
take X number of screenshots does not work 

### ISSUE THREAD

**Issue by thannemann** [nibogd/ingress-ice#44]
line number 214 of the ingress-ice file contains the wrong variable.  
			  0) WIDTH=`cat $tempfile`; break;;
should be 
			  0) NUMBER=`cat $tempfile`; break;;

**Comment by nibogd** [comment]
Thank you! Will fix soon. However, 4.0.0 will be released in a few days, where bash scripts are completely rewritten :)

**Comment by thannemann** [comment]
thanks I will wait till the new release as I am seeing a caching issue and the map not updating during captures from the first one

**Comment by nibogd** [comment]
It doesn't work with ultra-low delay like 30sec, 5 minutes is optimal. It
refreshes automatically as often as Ingress Intel map does.

**Comment by thannemann** [comment]
I am at 300 seconds, and the image is the same over a period of an hour, however on my laptop I was seeing activity and linking happening.  like I said it was almost like something was cached

**Comment by nibogd** [comment]
Hmm... That's strange. There is no caching. Maybe something is wrong with
internet connection?

вс, 6 сент. 2015 г. в 4:49, thannemann <notifications@github.com>:

**Comment by thannemann** [comment]
same internet connection different switch port, but I am ssh'd into the ingress-ice machine without an issue while it they are both on intel

**Comment by nibogd** [comment]
Maybe restart ice? I've no idea what's the reason for such behavior...

вс, 6 сент. 2015 г. в 4:54, thannemann <notifications@github.com>:
