### ISSUE TITLE
user agent causing problems with linux and iitc

### ISSUE THREAD

**Issue by nosybore** [nibogd/ingress-ice#47]
With 3.2.1 iitc mode works properly. In 4.0.0 iitc mode no longer shows portals. The stock version of intel still works as intended.

Running debian jessie.

**Comment by nosybore** [comment]
Figured it out - the user agent string. The linux version of phantomjs, when combined with iitc, results in no portals being displayed. Commenting out "page.settings.userAgent = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36';" in ice-config.js solves the issue.

**Comment by nibogd** [comment]
Oh, thank you! That's what i was afraid of. Will remove it later today.
10 сент. 2015 г. 3:10 пользователь "Paul Robison" <notifications@github.com>
написал:

**Comment by nibogd** [comment]
Fixed. Thank you!
