### ISSUE TITLE
Configuration creation is broken

### ISSUE THREAD

**Issue by schoentoon** [nibogd/ingress-ice#48]
With no config file in my home directory it does correctly recognize that I don't have one. After which it prompts if I want to create one. After I answer this with yes I get the following output.

```
Existing config file found (/home/.../.ingress-ice.conf). Starting ice...
ReferenceError: Can't find variable: quit

  /home/.../ingress-ice/ice/modules/ice-config.js:15

     _____ )   ___      _____) 
    (, /  (__/_____)  /        
      /     /         )__      
  ___/__   /        /          
(__ /     (______) (_____)  v4.0.0

If you need help or want a new feature, visit https://github.com/nibogd/ingress-ice/issues
TypeError: 'undefined' is not an object (evaluating 'page.open')

  /home/.../ingress-ice/ice/modules/ice-login-plain.js:26 in firePlainLogin
  /home/.../ingress-ice/ice/modules/ice-features-main.js:184 in ice
  /home/.../ingress-ice/ice/ice.js:39
```

**Comment by nibogd** [comment]
Em... Your home folder is really at `/home/.../`?!
Also, do you have bash installed?

**Comment by nibogd** [comment]
If the first is right, you may try creating a folder somewhere else (with no `...`), putting ice there and starting with `./ingress-ice -i <path to a new config>`.

**Comment by schoentoon** [comment]
My home directory isn't /home/.../ I masked out my username. And yes, I have bash installed.

**Comment by nibogd** [comment]
Hmm... You may try to manually `cp /path/to/ingress-ice/ice/ingress-ice.conf.sample /somewhere/else && nano /somewhere/else`, configure it and start ice using `./ingress-ice -i /somehere/else`.

And please show the output of `cat ~/.ingress-ice.conf`. Have you modified the script? Do you have rw access to your home folder?

Sorry for inconvenience, i have never faced this error :(

**Comment by nibogd** [comment]
Thank you for the report. I've figured out that `ReferenceError: Can't find variable: quit` happens when you haven't configured `login` or `password` or `link`, which are mandatory. It should show an error message, i'll fix that soon.

**Comment by schoentoon** [comment]
Should it pop up an editor with the config file after I've answered with yes? Because it doesn't even though it does seem to copy over the config file to my home directory (with indeed login, password and link missing).

**Comment by nibogd** [comment]
@schoentoon yeah, it should. It checks if the EDITOR variable is set, and if it is, calls `$EDITOR $HOME/.ingress-ice.conf~, if not, `nano $HOME/.ingress-ice.conf~

**Comment by schoentoon** [comment]
```
user@host ~/ingress-ice $ echo $EDITOR
/bin/nano
user@host ~/ingress-ice $ /bin/nano
-bash: /bin/nano: No such file or directory
```

I wonder why that doesn't work, lmao.. ```export EDITOR=vim```

**Comment by nibogd** [comment]
@schoentoon glad that you've figured out the reason :)
