### ISSUE TITLE
portal display zoom level

### ISSUE THREAD

**Issue by thannemann** [nibogd/ingress-ice#49]
At a zoom level of 15 or higher the portal information is not sent back to intel very well.  portals can be distroyed and refielded and still show old color.  need to stop ice and restart for them to display correctly.

I dont know if there is a fix for this, ie killing phantomjs between catures or something with phantomjs cache.

this is at a 300 second image rate.

**Comment by nibogd** [comment]
They should refresh anyway later. It's not an ice's bug and i can't do
anything with it. Maybe using ice with IITC will help?

пн, 21 сент. 2015 г. в 1:04, thannemann <notifications@github.com>:

**Comment by thannemann** [comment]
while I know it is not a direct error with your script, it is resolved by killing and relaunching your script.  Which leads me to beleive that there is some connection.  I was taking images every 300 seconds and an hour later they were still showing portals of one faction but links and fields of the other. the portals had not updated, I beleive this is related to phantomjs and how may be caching data between captures.  ie. are you killing phantomjs between each capture or just telling it to reresh the page

**Comment by nibogd** [comment]
It was refreshing the page before... That's not a good idea. There was a
memory leak (phantomjs) and speed was not good. IITC and timestamps didn't
work too because of phantomjs pags.
Killing phantom is also not good (there is no way to do it with
configuration like now and bash/cmd scripts).

As for now, ice works for me... Portals just update every 3 minutes or so,
less delay doesn't work. Do you have a good connection? Have you tried
using IITC?

**Comment by thannemann** [comment]
i am on a good connection, 105mb I have not tried ice with iitc white background if that is what you are asking, as I wanted stock looking intel.  If this is my only option I will look at a different soloution, thank you.

**Comment by WordfromtheWise** [comment]
Wasn't there a change with Intel map zoom Levels 1/2 a year ago where all OPs People complained that the map is now more of less useless. NIA wanted to lower server load for them with that change.

Best regards

**Comment by thannemann** [comment]
WordfromtheWise yes I agree there was a change with what was returned at different zoom levels, but the issue here is when I stop ice, and restart it I get accurate data if I dont restart the scripts then the portals show up with links being accurate, but the portals dont change hands if they are re-captured and fielded.

**Comment by nibogd** [comment]
Sorry, there is no way to fix that without completely rewriting ingress-ice. Maybe in the future, but not now.
