### ISSUE TITLE
Automated GIF creation

### ISSUE THREAD

**Issue by rawdr** [nibogd/ingress-ice#51]
I'm going to hack a way for a GIF to be created and updated with every screenshot. Properly optimized GIFs are actually a rather efficient way to store the consecutive images as only differences are saved. I'm not a programmer - I really wouldn't know the best way to integrate it with this tool.

But in linux I am going to simply use the imagemagick command as follows:
convert -layers Optimize -delay 20 -loop 0 layers.gif layers-(latest timestamp).png layers.gif

Running this with every new screenshot will add it's differences to the existing animated GIF (first run may omit the first 'layers.gif' input). Parameters such as delay can be put into config file.

If growing GIF filesize is an issue, maybe it can start a new file with every n minutes, or n snapshots, or n megabytes.

**Comment by nibogd** [comment]
Oh, thank you for the hint! I'll see if i can integrate this with
ingress-ice.

**Comment by nibogd** [comment]
Sorry for waiting so long… If you are still here. I'm afraid it's impossible to integrate it directly. However, you can do it by watching for filesystem changes, for example, using `inotify` watches (`man inotify`).
