### ISSUE TITLE
Config files, filenames, and parallel execution

### ISSUE THREAD

**Issue by rawdr** [nibogd/ingress-ice#52]
Do other people set up multiple instances for different views? It might make sense to have a directory for config files... any file put in that folder is a config file, thus the name of it can be used to name the snapshots themselves. 

So for example maybe I would create a file 'home' or 'home.conf' as well as a 'work.conf' file, that way I can have saved settings for each. When I want to run one, I just specify the name of the config file. Snapshots will be named similarly (and maybe in a folder with that name), still with their timestamps, so that snapshots with specific views are associated with each other and kept separate from other configs.

Running the script without a config could still run a default one... or perhaps it could give a numbered list of all config files and let you choose which to run.

I should point that I am aware of the -i parameter for inputing a config file name.

**Comment by nibogd** [comment]
I've used to have a config folder at `ingress-ice/configs` and to use it
like `./ingress-ice -i configs/park.conf`.
Is this what you want?

**Comment by nibogd** [comment]
*from the folder where screens should be saved
23 сент. 2015 г. 23:59 пользователь "Nikita B." <linuxoid.x64@gmail.com>
написал:

> I've used to have a config folder at `ingress-ice/configs` and to use it
> like `./ingress-ice -i configs/park.conf`.
> Is this what you want?
>

**Comment by rawdr** [comment]
Well I could easily create the folder myself and use the -i parameter. More important would be that png's are named after config file and stored in the subfolder.

Not necessary, just felt it would be more organized for multiple configs.
