### ISSUE TITLE
Raspberry Pi version

### ISSUE THREAD

**Issue by mogmismo** [nibogd/ingress-ice#53]
Works great, if you replace the phantomjs64 with a compiled binary for the arm processor.  Dropping this into the phantom-bin directory named phantomjs64 let's it work just fine.  You may want to include it in your original download. There are a few precomplied binaries out there in github, as it takes about 2 days to compile on that platform: https://github.com/aeberhardo/phantomjs-linux-armv6l

**Comment by nibogd** [comment]
Great, thanks. When i have time to do it i will add this to ingress-ice.
Thank you!

**Comment by nibogd** [comment]
Hm, sorry... I think i won't add it to ingress-ice — PhantomJS 1.9.6 is AFAIR the least ice requires :(

**Comment by mogmismo** [comment]
Here is another project that has compiled the 2.x version of phantomjs for the Raspberry Pi.  https://github.com/spfaffly/phantomjs-linux-armv6l  Don't need it myself (I already have a running copy), but others may want.

**Comment by nibogd** [comment]
Oh, thanks, this one should work :+1:

**Comment by nibogd** [comment]
Done in 7f57fcbafc248f937a333dba0fbcb3baf4f777d7
