### ISSUE TITLE
New argument

### ISSUE THREAD

**Issue by mcdoubleyou** [nibogd/ingress-ice#54]
Hello,

I'm not sure if this is the right way, but I hope somebody could help me.
In previous versions I was able to set own arguments by just write it on the end of config file and load with args[number], but at last version I don't know how settings loaded to JS.

Thank you!
mcdy

**Comment by nibogd** [comment]
Now there are only two arguments (patg to conf file and the number of
screenshots) which are passed to the script, other settings are read from
the `~/.ingress-ice.conf` file, which is formatted as a unix config or an
ini file: `argument=value`. They are available in the script as
`config.argument`.
