### ISSUE TITLE
PhantomJS causes QNetworkReply::ProtocolUnknownError on getPlexts.

### ISSUE THREAD

**Issue by ozero** [nibogd/ingress-ice#56]
any workaround?

- probrem:
PhantomJS causes QNetworkReply::ProtocolUnknownError (code:301) on getPlexts.

- platform:
Ubuntu 14.04.3 LTS
PhantomJS 1.9.8

- inconvenience:
I can't use player Tracker plugin.

- you can confirm by:

add ice-30-config.js
```
page.onResourceError = function(resourceError) {
  console.log('>> Unable to load resource \n' + JSON.stringify(resourceError,null,"  "));
};
```

add total-conversion-build.user.js : window.postAjax.onError
```
console.log(">>>> window.postAjax.onError\n"
+"(action:"+action+")\n"
+"(jqXHR: "+JSON.stringify(jqXHR,null,' ')+")\n"
+"(textStatus:"+JSON.stringify(textStatus,null,' ')+")\n"
+"(errorThrown:"+JSON.stringify(errorThrown,null,' ')+")");
```

**Comment by nibogd** [comment]
Looks like it doesn't follow a redirect... I'll look at it a bit later

**Comment by ozero** [comment]
Oh, code 301 shown above is not HTTP status code. 
It's a error code implemented in Qt's QNetworkReply Class.
http://doc.qt.io/qt-4.8/qnetworkreply.html

**Comment by ozero** [comment]
Hi, I confirmed /r/getPlexts are suppressed at page.onResourceRequested, intended to "aborting unnecessary API" on ice-30-config.js .
I commented out request.abort(); and getPlexts works fine. 
Thank you! > <

**Comment by nibogd** [comment]
Oh, thank you! I will remove that from master.

>
