### ISSUE TITLE
[Feature request] Detect if IITC need reloaded or is outdated and need update

### ISSUE THREAD

**Issue by sasha2002** [nibogd/ingress-ice#61]
Need to detect if IITC need reloaded or is outdated and need update.
If you run ICE but NIA after couple of time just updated botguard or temporarily banned you, you wouldn't be notified! 
And all screens contain the "magic" window name Reload IITC, that broke all GIF or video that you want to do :(

**Comment by nibogd** [comment]
Nice idea, will do this

**Comment by nibogd** [comment]
I'm awfully sorry for the delay 😢 Should work now, wasn't able to test.
