### ISSUE TITLE
armv6l version 4.2 issues with filename and version number

### ISSUE THREAD

**Issue by mogmismo** [nibogd/ingress-ice#66]
Script still shows version 4.1 and phantom-bin/phatnomjs-armv6l needs to be renamed to phantom-bin/phantomjs so the script can find the binary.  Thanks for adding a Raspberry Pi version, perfect use for a pi.

**Comment by nibogd** [comment]
Thank you. I've chaned the version number, need to re-upload files… 
Concerning the filename, could you please post the output of `uname -m` command?

**Comment by mogmismo** [comment]
Sorry about the delay:

$ uname -m
armv7l
$

Michael Tracey
Ponderwell, LLC
Phone - 1.828.423.0667
Email - michael@ponderwell.net
Web - http://ponderwell.net

**Comment by nibogd** [comment]
Sorry for being so late... Fixed everything. Thank you.
