### ISSUE TITLE
Multiple locations

### ISSUE THREAD

**Issue by MilkmanWes** [nibogd/ingress-ice#67]
A large city broken up into 4 quadrants, can I run one instance of this and have it take a shot of each quadrants link or do I need to run 4 instances?

If not, can it run once and quit so I could just keep supplying a new URL from a list via a cron job?

**Comment by nibogd** [comment]
Sorry, you need to run 4 instances, it's a limitation of PhantomJS.

You can make 4 configuration files with a limit of 1 screenshot and start ice with different configs via a cron job
