### ISSUE TITLE
Config ingress-ice.cmd update

### ISSUE THREAD

**Issue by kameleon20** [nibogd/ingress-ice#69]
The config file is now saved in the %APPDATA%\local\tmp folder, but why not saving it in a config folder inside the root of ingress save like .\config\.ingress-ice.conf

Pro's are that you can use it for multiple timelapses a time with different credentials if needed.

it will look like this:
set FILE=".\config\.ingress-ice.conf"

Tested it for myself and it's working

**Comment by nibogd** [comment]
Hm, maybe you are right...
The other side of this, if you just delete and unpack a new version of ingress-ice, you will have to configure it again. I'll think about it...

**Comment by nibogd** [comment]
I've decided not to change the default, but now (with git version or release v4.3.0 when ready) you can place a file named `ingress-ice.conf` into the ice root and copy your settings, it will be used for configuration.
