### ISSUE TITLE
screenshot save location

### ISSUE THREAD

**Issue by kameleon20** [nibogd/ingress-ice#70]
can the screenshots be saved in a sub folder like screenshots? it's tidier this way, and it feels half-baked now

**Comment by jelleruben** [comment]
I hope it can. I like to save the capture in an other directory too.

**Comment by nibogd** [comment]
On Linux you can just start it from any folder and it will save screenshots into it. On Windows, this is not available yet, will do it in a few days

**Comment by nibogd** [comment]
Done (in the git repo, will release later). Update your config files — edit the `directory` variable.

**Comment by kameleon20** [comment]
Woohoo thanks!
