### ISSUE TITLE
docker: additional config file location in the screenshot dir

### ISSUE THREAD

**Issue by JanSchulz** [nibogd/ingress-ice#71]
I Installed ingress-ice on my NAS and wanted to run it in a docker container. Unfortunately, the NAS UI does not allow for for files to be linked (`-v file`) into the container, only directories. So it would be nice to have the docker startup also look for the file in the screenshot directory if the file isn't found in normal location.

**Comment by nibogd** [comment]
Sorry, i don't understand, how could i do this :sweat_smile:

**Comment by JanSchulz** [comment]
Something like this (untested as I do this from a windows PC):

```diff
diff --git a/docker-ingress-ice.sh b/docker-ingress-ice.sh
index 64821f0..6714513 100644
--- a/docker-ingress-ice.sh
+++ b/docker-ingress-ice.sh
@@ -1,14 +1,21 @@
 #!/bin/bash
 
 config_file="/.ingress-ice.conf"
-screenshot_folder="/screenshots/"
+screenshot_folder="/screenshots"
 if ! [[ -r "$config_file" ]]
 then
-	echo "The configuration file does not exists. Please create it first and then specify it as a docker volume!" >&2
+	echo "Normal configuration file does not exists. Searching for config file in screenshot folder" >&2
+	config_file="${screenshot_folder}/.ingress-ice.conf"
+fi
+
+if ! [[ -r "$config_file" ]]
+then
+	echo "The configuration file does not exists. Please create it first and then specify it as a docker volume or put it into the screenshot folder!" >&2
 	exit 1
 fi
 
+
 umask 0000
 
-cd /screenshots
-phantomjs /ingress-ice/ice/ice.js /.ingress-ice.conf > ingress-ice.log
+cd ${screenshot_folder}
+phantomjs /ingress-ice/ice/ice.js /${config_file} > ingress-ice.log
```

**Comment by nibogd** [comment]
Thank you! Didn't understand that directories can be linked :sweat_smile:  Will add this when i get to my linux machine (i hope in a day)

**Comment by JanSchulz** [comment]
sorry, probably wrong name: I mean the "bind mount a volume" thingy (`-v`). In the NAS UI, you can only chose folders, not files, but it's possible on the commandline.

**Comment by nibogd** [comment]
Sorry for the delay (there were some unexpected problems :sweat: ), done it. Place config at `/screenshots_volume/.ingress-ice.conf` and it will be loaded. Will rebuild Docker Hub image in several minutes.

**Comment by JanSchulz** [comment]
Thanks a lot!
