### ISSUE TITLE
make timeouts configureable?

### ISSUE THREAD

**Issue by JanSchulz** [nibogd/ingress-ice#72]
I tried to install ingress-ice on a nas (QNAP 253 Pro, docker container, Celeron 2.0GHz quad-core processor, 4GB ram), and I couldn't get it to run: first problems with authenticating (probably unrelated...) and then I only got an empty map (no portals, no links/fields). I tried to increase the timeouts and since then it works. I'm not sure if that was the problem or if there is anything else which could result in empty maps. 

If that could result in such a result, it would be nice if the timeouts could be changed in the config files (I change the following, the loginTimeout might be a bit much :-))

```diff
diff --git a/ice/modules/ice-30-config.js b/ice/modules/ice-30-config.js
index ed62e62..35f187c 100644
--- a/ice/modules/ice-30-config.js
+++ b/ice/modules/ice-30-config.js
@@ -41,7 +41,7 @@ var curnum       = 0;
 * Delay between logging in and checking if successful
 * @default
 */
-var loginTimeout = 10 * 1000;
+var loginTimeout = 100 * 1000;

 /**
 * twostep auth trigger
diff --git a/ice/modules/ice-60-features-main.js b/ice/modules/ice-60-features-main.js
index 5934df1..7f6e1d6 100644
--- a/ice/modules/ice-60-features-main.js
+++ b/ice/modules/ice-60-features-main.js
@@ -188,7 +188,7 @@ function main() {
     file = folder + lastScreen;
     s(file);
     postprocess(lastScreen);
-  }, 2000);
+  }, 5000);
 }

 /**
```

**Comment by nibogd** [comment]
Please wait a few days till i do this

**Comment by nibogd** [comment]
Done (in git repo, release a bit later)

**Comment by JanSchulz** [comment]
I will test but afair I also had to increase the timeout for the actual screenshotting...

**Comment by nibogd** [comment]
Timeout for screenshotting is also configureable in the config file :)

**Comment by nibogd** [comment]
Ah, sorry, misunderstood. Will add this too

**Comment by nibogd** [comment]
Looked at it again, haven't found other timeouts depending on internet connection (implying the problem is the internet connection)…
