### ISSUE TITLE
Save all console messages to log file

### ISSUE THREAD

**Issue by mogmismo** [nibogd/ingress-ice#74]
A great enhancement/feature would be the ability to get a date/time stamped text log file of every console log message in the area along with the images.

**Comment by nibogd** [comment]
You mean, chat log? See #60 . Sorry, can't do this.

**Comment by schoentoon** [comment]
Pretty sure @mogmismo means the messages from ingress-ice itself.

**Comment by nibogd** [comment]
That is possible. Waiting for @mogmismo to confirm.

**Comment by nibogd** [comment]
Sorry for the delay, if it's what you wanted, it's implemented in 9b65ec
