### ISSUE TITLE
phantomJS outdated with debian Jessie on RPi

### ISSUE THREAD

**Issue by dampen** [nibogd/ingress-ice#77]
It asks for libicudata.so.48 that is not included in Debian jessie on raspberry pi. libicudata.so.52 is the most recent 

Error message: 
phantomjs-armv6l: error while loading shared libraries: libicudata.so.48: cannot open shared object file: No such file or directory

**Comment by nibogd** [comment]
Does the latest PhantomJS work? Is there a way to install those libs?

>

**Comment by dampen** [comment]
I added a backport to wheezy and managed to install the libicu48 and made it work that way. But it seems unstable, stops screenshoting after a number of screens (last night after 273) and giving a phantomJS error. On the other hand im trying to run it on an quite old raspberry (1 gen) Have not had these problems on my regular server

**Comment by jbouse** [comment]
Just my suggestion... I don't have ICE running on my RPi right now but I have it running a hybrid Jessie/Stretch Raspbian install... It has PhantomJS 1.4.1 already packaged and available with all dependencies... Would it not be just as easy to use the distribution version if available and installed?

**Comment by nibogd** [comment]
@jbouse i tried to do so (use the distribution's PhantomJS), it turned out that ~1.9.2 is the minimal version which works with ice and users who had phantom <1.9 didn't understand why doesn't ice work

**Comment by nibogd** [comment]
@dampen hm, i think i'll update PhantomJS in the repo after a bit of testing. Also need to fix Docker support and will release a new version with latest Phantom :)

**Comment by nibogd** [comment]
Updated PhantomJS for all platforms except armv6l in b476f67bedc6b78c0156957f5873b91570692d80
Couldn't find a newer version available for arm — that one in the repo is 2.0.1 :(

**Comment by jbouse** [comment]
I got it working on my Raspberry Pi with the armv6l release... I simply needed to install the libicu48 package from Wheezy over my Jessie/Stretch hybrid Raspbian install.

**Comment by nibogd** [comment]
@jbouse hm, nice :) Does it work well?

@dampen Sorry, I can't do anything with this issue. Will add this workaround to the documentation and close the issue :(

**Comment by jbouse** [comment]
@nibogd After grabbing  http://mirrordirector.raspbian.org/raspbian/pool/main/i/icu/libicu48_4.8.1.1-12+deb7u3_armhf.deb and installing it on my Raspberry Pi it has been working like a champ... I've got it taking screenshots of my local area every 5 minutes now. If I could just figure out the AWS S3 upload issue (#83 which isn't specific to the Pi as it fails from my Windows and Linux machines as well) it'll be perfect.

**Comment by nibogd** [comment]
@jbouse Nice, thanks for report :)

**Comment by nibogd** [comment]
Added info about this dependency [here](https://github.com/nibogd/ingress-ice/wiki/Dependencies-(Linux)), closing the issue.
