### ISSUE TITLE
Debian 8.3 Cross-Domain error

### ISSUE THREAD

**Issue by Jack992** [nibogd/ingress-ice#78]
Error on Debian 8.3:
> Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///root/ingress-ice/ice/ice.js. Domains, protocols and ports must match.

Same config is working on my MacBook, but not on my Debian-Server.
Ice Version: 4.2.0

**Comment by nibogd** [comment]
I sometimes have this error, but it doesn't prevent ice from working. Does ice work after that? If yes, just ignore it. You can also try updating phantomjs executable

**Comment by Jack992** [comment]
No, it doesn´t work after that. Here the complete output:

> root@xyz(ingress-ice)# ./ingress-ice.sh
Existing config file found (/root/.ingress-ice.conf). Starting ice...
     _____ )   ___      _____)
    (, /  (__/_____)  /
      /     /         )__
  ___/__   /        /
(__ /     (______) (_____)  v4.2.0
If you need help or want a new feature, visit https://github.com/nibogd/ingress-ice/issues
15.02.2016 13:31:02 GMT+0100 (CET): Using cookies to log in
15.02.2016 13:31:03 GMT+0100 (CET): Logging in...
15.02.2016 13:31:15 GMT+0100 (CET): Validating login credentials...
15.02.2016 13:31:25 GMT+0100 (CET): Something went wrong. Please, sign in to Google via your browser and restart ICE. Don't worry, your Ingress account will not be affected.
15.02.2016 13:31:25 GMT+0100 (CET): Quit
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///root/ingress-ice/ice/ice.js. Domains, protocols and ports must match.
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///root/ingress-ice/ice/ice.js. Domains, protocols and ports must match.
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///root/ingress-ice/ice/ice.js. Domains, protocols and ports must match.
root@xyz (ingress-ice)#

Now i´ll try to update phantomjs.

**Comment by Jack992** [comment]
It looks like the SACSID wasn´t copied correctly. (No problem with phantomjs)
But why did it work on the MacBook with the exact same conf file?
No matter, it is working now. Layer 8 Problem :-)

**Comment by nibogd** [comment]
Glad that you solved it :smile: 
>But why did it work on the MacBook with the exact same conf file?

It may be different IP address or some other Google's traps for bots
