### ISSUE TITLE
Too much CPU in phantomjs

### ISSUE THREAD

**Issue by JanSchulz** [nibogd/ingress-ice#79]
I'm running ingress-ice in a docker container on my nas. It's configured to take a screenshot every two hours. Unfortunately, the NAS is constantly having high CPU due to phantomjs using a whole CPU (=25% CPU) almost at all times.

I just tried to run it on my local windows desktop (same config -> screenshots every two hours) and almost the same happens: 25% CPU most of time, only every few minutes is a small break. 

Ist there any way to prevent phantomjs from doing whatever it is doing until the next screenshot comes up?

**Comment by nibogd** [comment]
I think there is no way to reduce processor usage, sorry :sweat:

**Comment by JanSchulz** [comment]
Ok :-( What is actually running there? Refresh scripts of the intel map? If yes: could these be disabled?

Would it be reasonable to implement a "start ingress-ice, take *one* screenshot, kill phantomjs, wait xxx minutes, start ingress-ice" mode?

**Comment by nibogd** [comment]
I think no :sweat: It takes much time to load and it would need different code on each platform.
> Ok :-( What is actually running there? 
Background scripts, those which usually run on http://ingress.com/intel :(

**Comment by JanSchulz** [comment]
One idea: instead of running the screenshotting code in a loop, simple start, screenshot, [exit](http://phantomjs.org/api/phantom/method/exit.html). Then run the docker container (or the normal script; not sure if that's possible out of the box on the QNAP NAS) from crontab.

That would need a config variable which makes the script not run main in a loop (e.g. [here]( https://github.com/nibogd/ingress-ice/blob/544f4070f8e9eefd8524062172ca774233bde2d4/ice/modules/ice-80-login-plain.js#L124) and [here](https://github.com/nibogd/ingress-ice/blob/a7bd1a48e9faa03365e59c434ced06b1ca909fcb/ice/modules/ice-70-login-cookies.js#L103))

Another idea: does IITC also run the idle scripts? I remember they had some code which made reloads earlier than the default, so it should be possible to also delay these reloads until the next screenshot time?

**Comment by nibogd** [comment]
@JanSchulz the problem is, Docker containers are heavy and not easy to use (and not available on windows)
I'll look into IITC's code, may be it's possible. I will also update PhantomJS (#77), hope it is optimized better :)

**Comment by JanSchulz** [comment]
If windows support ist the only problem, I can also add/update the windows script to work with that (or better add an example how to call the script as a kind ws task every x hours). :-)

**Comment by nibogd** [comment]
That isn't the only problem. It is not easy to use and it would fail with bad internet connection :(

**Comment by JanSchulz** [comment]
@nibogd I actually don't mind if it would be a "you need to setup on your own" if e.g. setting `delay=-1` would exit phantomjs after the first screenshot. (for better logging, it should probably also append to the logfile and not overwrite it, but that's secondary...).

**Comment by nibogd** [comment]
Hm, linux version of ice has an option to make a specific number of screenshots. You can use `./ingress-ice.sh -c 1` to take a single screenshot and exit. I think i'll implement that `delay=-1` setting for windows.

**Comment by JanSchulz** [comment]
If I read this right... 

```
$PHANTOMJS "$SCRIPT_HOME/ice/ice.js" $ARGS; exit;
```

...it should also work on every platform? 

I can add some commandline parsing to the cmd file to also accept `-c x`, if you would take such a patch?

**Comment by nibogd** [comment]
Would be nice!
`delay=-1` to take a single screenshot and exit implemented in 4d0bc64588780e0fe5b109948846cd7a658448dc

**Comment by JanSchulz** [comment]
Can be closed, implemented in https://github.com/nibogd/ingress-ice/pull/81 (you are to fast :-))
