### ISSUE TITLE
New feature request: filter by portal level

### ISSUE THREAD

**Issue by adostes** [nibogd/ingress-ice#8]
It would be great to have the possibility to filter by portal level, or even hide all portals.

**Comment by nibogd** [comment]
I've done that you requested, the release will be uploaded soon :smile:. Now it comes with a separate configuration file, if you won't understand how to configure it, feel free to make a new issue.

Thank you for using ingress-ice! :blush:

**Comment by nibogd** [comment]
Ah, sorry, forgot to say that hiding all portals is impossible :swear:

**Comment by adostes** [comment]
Very cool, thanks for the quick turnaround! I did find a couple of very small issues, I'll do a pull request, thanks :+1:
