### ISSUE TITLE
Move PhantomJS binaries to Git-LFS

### ISSUE THREAD

**Issue by nibogd** [nibogd/ingress-ice#80]
We should move PhantomJS binaries to Git-LFS or completely remove them from the repo for better optimization. The drawback is that ![Download ZIP](https://cloud.githubusercontent.com/assets/2771136/12703381/36d9adb4-c85b-11e5-81b1-ec0dbef9f679.png) button won't download Git-LFS files and everybody will need to install Git-LFS before making pull-requests. What do you guys think about it?

**Comment by JanSchulz** [comment]
Please not git-lfs, that means you have to setup that system to get it running.

There are probably a few ways to download a file on windows without installing wget/curl first (e.g. https://stackoverflow.com/questions/4619088/windows-batch-file-file-download-from-a-url), so maybe adding a `prepare.cmd` command (and the equivilent sh file) might be a way to go.

**Comment by nibogd** [comment]
Thank you for the reply. I thought about moving files in repo into git-lfs, but usual downloads through releases would work as they do now. But if it's unavailable for some users, i won't do it.
