### ISSUE TITLE
Make it possible to overwrite the URL+screenshot dir via a commandline parameter

### ISSUE THREAD

**Issue by janschulz** [nibogd/ingress-ice#82]
This would make it possible to call ? `ingress-ice -c 1 -url http://.... -screenshots ./screens1` and get back one screenshot in `./screens`. It would also be possible to use the same config file (login, etc) for multiple intel map locations.

My evil plan is it to drop a file into a dir which specifies `2h|./screens2|<url>` and a watchdog script (just found one in python) would translate that into a cron run every two hours for the URL which would put the screens in `./screens2`. Then I could run this as a docker image on my NAS and only have to add a new line to get screenshots for a different location...

So: would you take such a patch (I think I can give you the JS, cmd and probably also the bash part and also could add a dockerfile for the idea above...)

**Comment by nibogd** [comment]
Hm… I think that's too compicated :grin:
But let it be, it's useful. Would be nice :) If you are not good at bash, i can do that part

**Comment by nibogd** [comment]
Are you still going to implement this? If yes, please remove your ingress-ice fork and fork it again (see #91 for details). If no, i will close the issue.
