### ISSUE TITLE
Process killed

### ISSUE THREAD

**Issue by kelt8** [nibogd/ingress-ice#84]
Getting the process killed after running the script

> ./ingress-ice.sh: line 35: 11437 Killed                  $PHANTOMJS "$SCRIPT_HOME/ice/ice.js" $ARGS

It seems to be happening on new Google account, have no issues logging into Intel or app. Switching to an old Google account would work. Any insights would be helpful!

**Comment by nibogd** [comment]
Strange
Maybe it's getting killed trying to exit — should display a message, but does nothing and exits

Which is your OS?

**Comment by jbouse** [comment]
I've also had that happen to me a couple times now on my Raspberry Pi... restarting it up works fine again but it just spontaneously stops.

**Comment by kelt8** [comment]
nibogd, Linux, both Debian and Ubuntu versions. Although no 2 factor has been setup, its asking for sometimes, only happens to new account.

**Comment by jbouse** [comment]
This is what I get... I've even disabled 2-factor authentication on the account I'm using.

```
ExceptionHandler::GenerateDump waitpid failed:No child processes
PhantomJS has crashed. Please read the crash reporting guide at
<http://phantomjs.org/crash-reporting.html> and file a bug report at
<https://github.com/ariya/phantomjs/issues/new>.
Unfortunately, no crash dump is available.
(Is $TMPDIR (/tmp) a directory you cannot write?)
./ingress-ice.sh: line 25:  7937 Segmentation fault      $PHANTOMJS "$SCRIPT_HOME/ice/ice.js" $ARGS
```

This is on  my Raspberry Pi running Raspbian

**Comment by nibogd** [comment]
@kelt8 yep, sometimes google suspects us in using bots or something… I don't know how to solve this problem :( in my case it was my provider, worked with other ISPs

**Comment by nibogd** [comment]
@jbouse seems like a PhantomJS error :sweat:
You may try using an older version of phantom (not sure, but it could be more stable), for example, [this](https://github.com/xlsdg/phantomjs-linux-armv6l/releases) (replace `phantom-bin/phantom-armv6l` with the file from archive)

**Comment by jbouse** [comment]
@nibogd I see that the version you have in the release is:

```
./ingress-ice-armv6l/phantom-bin/phantomjs-armv6l --version
2.0.1-development
```

I see if I upgrade fully from Jessie to Stretch (instead of running a hybrid) that PhantomJS 2.1.1 is available. That appears to match what is in the win32 release as well so I'll give that a shot.

**Comment by jbouse** [comment]
@nibogd I did downgrade to 1.9.8 and it still causes the crashes but I wrapped the call inside a while loop that at least keeps it running consistently I just have to remove the bad images before rendering the video.

Running it using
`while true; do ./ingress-ice.sh ; done`

**Comment by nibogd** [comment]
Hm, at least it works… Will try to somehow add this option, @jbouse

**Comment by nibogd** [comment]
Now ICE for linux has option `-s`, which runs it in an endless loop.

**Comment by victaru** [comment]
the -s option doesn't solve the issue..

**Comment by kelt8** [comment]
@victaru maybe this can help you temp. to inform you when the script exits abnormally. generally on vps, for 1GB ram (2 instances of ice running) anything more it will exit automagically after sometime.

in the ingress-ice.sh file, line 53.
I changed this
      $PHANTOMJS "$SCRIPT_HOME/ice/ice.js" $ARGS; exit;

to

    $PHANTOMJS "$SCRIPT_HOME/ice/ice.js" $ARGS; echo "email title" | mail -s bodyline hello@youremail.com; exit;
