### ISSUE TITLE
[Feature Request] Dropbox upload

### ISSUE THREAD

**Issue by jbouse** [nibogd/ingress-ice#85]
I've not worked with PhantomJS before myself but would be willing to help give a shot if I could get some guidance. Just as we have the AWS S3 upload (which for me hasn't worked) I was considering the possibility of using my Dropbox and using the [Saver](https://www.dropbox.com/developers/saver).

I've worked with some other projects that used the Dropbox Chooser to download files but I haven't tried working with the Saver although the documentation looks similar. Just reall unsure how to add it to PhantomJS/ICE.

**Comment by nibogd** [comment]
Hm, nice idea, will try to add :)

**Comment by nibogd** [comment]
Oh, if you want to code it yourself, see [contribution guide](https://github.com/nibogd/ingress-ice/blob/master/CONTRIBUTING.md). You can make a module with number less then 30 (explained in the guide) and call your function from `postprocess` in `ice/modules/ice-60-core.js`

**Comment by jbouse** [comment]
If I can find some spare cycles I'll try and take a stab at it. I had seen how `postprocess` was calling the AWS S3 upload while I was trying to trace the issues I'm having with it apparently not uploading. I just haven't done much with JS or PhantomJS myself before. If it were Python I'd be much more at home.

**Comment by c2nprds** [comment]
https://www.dropbox.com/en/install?os=linux
set and config `./screenshots` directory
auto sync screenshots directory.

This is so bad?

**Comment by nibogd** [comment]
@c2nprds that's a great solution, but i doubt it will work with Docker…

**Comment by schoentoon** [comment]
@c2nprds @nibogd That's a solution that will only work when you actually have the storage for it. In which case any kind of 'cloud' storage doesn't make sense at all anyway. I think OP wants a dropbox upload without the client having to sync it.
