### ISSUE TITLE
Timestamp not appearing in screenshot 

### ISSUE THREAD

**Issue by victaru** [nibogd/ingress-ice#88]
I've set the timestamp value to true yet it still doesn't appear in my screenshots... Any idea why?

**Comment by nibogd** [comment]
Which OS and PhantomJS version are you using? Do you use IITC? Could you post your config file (without login and password)?

**Comment by victaru** [comment]
# This is a configuration file for Ingress Ice (github.com/nibogd/ingress-ice)                        # Insert your settings here (after '=' without spaces). Only first three settings (login, password and area link) are mandatory.
#
# After modifying this file, save it and close the editor. Ice will start automatically.
[ice]
#> Your Google login and password
login=<redacted>                                                                  password=<redacted>                                                                            #> Your area link. To get it, visit http://ingress.com/intel, scroll the map to your location and press [LINK] at the top right corner. Copy that link and paste it here.
#> e. g. https://www.ingress.com/intel?ll=53.502328,49.41516&z=14                                     area=https://www.ingress.com/intel?ll=1.294717,103.782635&z=13                                        [ice-optional]                                                                                        #> The delay between taking screenshots in milliseconds (1 second = 1000 milliseconds). Set to -1 to take a single screenshot and exit
delay=300000
#> Minimal and maximal portal levels to display                                                       minlevel=1
maxlevel=8                                                                                            #> Width and height of the resulting screenshot                                                       width=500
height=500                                                                                            #> Inject IITC? (true/false)
iitc=true                                                                                             plugins=["https://secure.jonatkins.com/iitc/release/plugins/player-tracker.user.js"]                  # Read more at https://github.com/nibogd/ingress-ice/wiki/Loading-IITC-plugins                        pluginsConfig=[{"key":"plugin-linkshowdirection-mode","value":"Static near origin"},{"key":"YourKeyHere","value":""}]
#> Put a timestamp on your screenshots? (true/false)                                                  timestamp=true
#> Hide Resistance portals/links/fields, Enlightened portals/links/fields, links, fields respectively? (true/false)
hideRes=false
hideEnl=false                                                                                         hideLink=false                                                                                        hideField=false                                                                                       # Picture format (png/jpg)                                                                            format=png                                                                                            #> Log in timeout. Default is 10 000 (ms). If you have problems with signing in, increasing this may help                                                                                                   loginTimeout=10000                                                                                    #> Directory (folder) where to save screenshots. Note the trailing slash. Relative to the current location. In linux, you can start it from any folder like this:
# $ some-folder/ingress-ice/ingress-ice.sh                                                            directory=/screenshots/
#> Add timezone to timestamp? (true/false)
timezone=true

[cookies]
#> If set, will use cookies for authentication instead of login/password                              SACSID=
CSRF=

[Amazon-S3]
#> If set, will upload screenshots to Amazon S3 cloud
#> AWS S3 accessKeyId
S3Key=
#> AWS S3 secretKeyId
S3Secret=
#> AWS S3 bucket name
S3Bucket=
#> AWS S3 access control list
S3Alc=                                                                                                #> Delete files after upload? (true/false)
S3Remove=false

[version]                                                                                             version=43
~                                                                                                     ~                                                                                                     ~                                                                                                     ~                                                                                                     ~
-----------------

I'm on CentOS 7, not sure what version of phantomJS, but it's dated April 18

**Comment by nibogd** [comment]
Thank you, I'll look if i can do anything with it

**Comment by victaru** [comment]
so i took the default config file and did a re-run, and the timestamp came out. on a whim i decided to play with the screenshot width and height value, and i realised that it could be that my current setting of width=500 is causing the timestamp value not to appear.

**Comment by nibogd** [comment]
@victaru yep, it must be that setting. Too narrow for a timestamp.
Glad that you've found out the problem! Closing the issue.
