### ISSUE TITLE
Draw Polygons on iitc?

### ISSUE THREAD

**Issue by victaru** [nibogd/ingress-ice#89]
hihi,

I'm trying to get a polygon drawn using IITC Draw tools to appear in the screenshot, so i amended the .conf files as follows:

plugins=["http://iitc.jonatkins.com/release/plugins/draw-tools.user.js" ]

pluginsConfig=[{"key":"plugin-draw-tools-layer","value":"[{'type':'polygon','latLngs':[{'lat':28.550402302762,'lng':-81.366473436356},{'lat':28.551476653534,'lng':-81.363168954849},{'lat':28.548705937122,'lng':-81.360669136047},{'lat':28.547348824935,'lng':-81.361935138702},{'lat':28.54683047886,'lng':-81.364177465439},{'lat':28.547575011514,'lng':-81.366001367569}],'color':'#a24ac3'}]"}]

however it doesn't appear...any one tried this before?

**Comment by nibogd** [comment]
Hi,
Thank you for the report. Don't currently have time, but i'll test that later, it should have worked…

**Comment by victaru** [comment]
Closing this issue. I replaced the double-quotes to single quotes, which won't work, so for this to work, all the double-quotes has to be escaped with the backslash (\) i.e. \"

**Comment by nibogd** [comment]
Nice, thank you! I will add this to the documentation
