### ISSUE TITLE
take snapshot at predefined time, ie. at checkpoints

### ISSUE THREAD

**Issue by triune** [nibogd/ingress-ice#90]
There seems to be a random startup interval between the time the script is executed and the time when the first screenshot is taken. This makes it very difficult to predict at what time exactly the first screenshot will be taken. In my use-case I would like to only take screenshots every 5 hours exactly at the checkpoint, or perhaps 10 seconds later to allow intel latency or clock drift.

Is there some way to accurately predict when ice will take the first screenshot? Else, could we add an additional configuration parameter, let's call it **cron** that will execute the screen capture timing according to a crontab syntax?

**Comment by nibogd** [comment]
Nice idea. I doubt we can take a screenshot at the exact time, but if the largest drift is between the script start and the first screenshot, it is possible to delay the screenshot. Not sure about crontab syntax, i'll see...

**Comment by triune** [comment]
If I could start the script at any time (@reboot crontab) and just have it delay the first screenshot until 10 seconds after the hour, that would solve everything!

To note, I've run the script for several days now and after the first screenshot is taken all subsequent shots follow the predefined interval exactly to the second (no variance/drift).

**Comment by nibogd** [comment]
Thank you for details!
Sorry, it may take several days or more due to me having exams, but i'll do that

**Comment by triune** [comment]
Best of luck on your exams 👍

**Comment by nibogd** [comment]
Thank you! :wink:

**Comment by triune** [comment]
@nibogd hey, forget wasting your time on this... for some reason, running ice on my GCE instance... from startup to first screenshot is always 16:03 ... so I can just cron startup at :44 after the hour, take a screenshot at like 12:00:03, and then kill the script (so IITC refreshes on next load and is never stale). This works for me!

**Comment by nibogd** [comment]
Weird O.o Anyway, such a feature would be useful. if it isn't too hard, i'll implement it.

By the way, try setting the delay to -1 instead of killing the script, it will take a single screenshot and exit itself.

**Comment by triune** [comment]
Thanks for that tip! That's much easier / more elegant than writing a script to detect the PID and killing it :)
If you still want to implement this, I'll be sure to test it out for ya. But, more pressing of an issue is https://github.com/nibogd/ingress-ice/issues/61 reloading IITC imo.

**Comment by nibogd** [comment]
#61 is hard :grin:
Yep, surely i must pay a bit more attention to it...

**Comment by nibogd** [comment]
Now i have time to do this. Thinking about it, afaik there is no way to specify checkpoint in cron format. And if i make an option to specify time or to just wait for the next checkpoint, it would be very inflexible. What do you think about it? And anyway, would you like to see this feature in ICE? If it's useless now, it's better to keep ICE smaller not adding it...

**Comment by triune** [comment]
@nibogd as I mentioned previously, I'm just interested in taking hourly screenshots. I make gifs with 24 images per day for my local region. The feature here really isn't necessary as I thought, but #61 definitely screws things up for me once in awhile and I'm sure for others too. I'd close this and work on that instead ;)

**Comment by nibogd** [comment]
oh, ok :)
