### ISSUE TITLE
Remove binaries from the repo

### ISSUE THREAD

**Issue by nibogd** [nibogd/ingress-ice#91]
After GitHub update, ![Download ZIP](https://cloud.githubusercontent.com/assets/2771136/12703381/36d9adb4-c85b-11e5-81b1-ec0dbef9f679.png) button became more obscure, users won't be clicking it if they don't know what is it for. And according to my stats, more users are downloading Ingress ICE from the website, and links there refer to GitHub releases. So, binaries in the repo are useless now. They consume a lot of space and bandwidth and i'm going to remove them from the repo **history**.

#### What does it mean?
 - Users must download Ingress ICE from [releases](https://github.com/nibogd/ingress-ice/releases) section or from the website (preferred way).

 - Developers of forks will need to rebase instead of pulling/merging. I'll post detailed instruction after i push the repo with rewritten history.

**Comment by nibogd** [comment]
Will now push repo with modified history. To keep the ability to merge with master if you have a fork, do the following.

Firstly, backup your repo:
```bash
$ git clone --mirror https://github.com/YOURNAME/ingress-ice
```

Then rewrite the history in the same way i did it:
```bash
$ git clone https://github.com/YOURNAME/ingress-ice
$ cd ingress-ice/ # directory with your fork
$ git filter-branch --force --index-filter 'git rm --ignore-unmatch -rf phantom*' --prune-empty --tag-name-filter cat -- --all
```

Collect the garbage...
```bash
$ git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin
$ git reflog expire --expire=now --all
$ git gc --prune=now
```

...and push the changes
```bash
$ git push -f --all origin
$ git push -f --tags origin
```

Yay! Now the repo is way smaller!
I am sorry for incovenience, this is needed to keep repo small.

If your fork isn't any different from this repo, it's better to delete yours and fork it again.

If you want to get a copy of old fat repo, ask me, i have a backup. If you find that something else besides phantomjs binaries has changed/has been removed, also contact me.

**Comment by janschulz** [comment]
If you don't care about the size of your local clone and just want to get your PR working against the new master:

```
# in your local branch
git fetch origin # assuming upstream is called origin in your setup
git rebase origin/master
git push -f
```
