### ISSUE TITLE
pull regional score information from IITC and save to disk in JSON file

### ISSUE THREAD

**Issue by triune** [nibogd/ingress-ice#92]
This would be an awesome feature to have. My bot can watch the file and report local scores to agents! Would suggest that the score is checked and saved to disk in tandem with the screenshot interval.

**Comment by nibogd** [comment]
Isn't this an idea for another utility?
I have [this](https://github.com/nibogd/tg-ingress-scorebot) repo which does the same thing, i can extract that function and create a separate tool. Because i don't wanna make Ingress-ICE bloated :grin:

**Comment by triune** [comment]
Touche! I wasn't aware of the other utility, yes please close this too.

**Comment by nibogd** [comment]
Oh, that one is intended to be used with Telegram and it creates diagrams and works as a Telegram bot. [Here](https://github.com/nibogd/tg-ingress-scorebot/blob/master/crawler.js) is the file which crawls the scores, hope you will figure out how to use it ;) Ask me if you need help
