### ISSUE TITLE
Cannot Connect to remote server

### ISSUE THREAD

**Issue by gruessung** [nibogd/ingress-ice#93]
I only See the following message in my raspi:

`Existing config file found (conf.conf). Starting ice...
/home/tmpuser/scan/ice/ice.js conf.conf 0

     _____ )   ___      _____)
    (, /  (__/_____)  /
      /     /         )__
  ___/__   /        /
(__ /     (______) (_____)  v4.0.1

If you need help or want a new feature, visit https://github.com/nibogd/ingress-ice/issues22.07.2016 04:58:19: ICE crashed. Reason: cannot connect to remote server :(
pi@raspi1:/home/tmpuser/scan $`

**Comment by gruessung** [comment]
I have to append --ingore-ssl-errors=true and --ssl-protocol=any in ingress-ice.sh to $PHANTONJS.

**Comment by nibogd** [comment]
Glad you've solved the problem yourself. Could you tell me which version of PhantomJS are you using? It may be that outdated version doesn't fit modern TLS requirements.

**Comment by gruessung** [comment]
I usw 1.9.0

**Comment by nibogd** [comment]
Oh, yep, you'd better use at least 1.9.3. But if it works, it's ok.
