### ISSUE TITLE
Login not possible -> verify your account prompt

### ISSUE THREAD

**Issue by gruessung** [nibogd/ingress-ice#97]
I use login/pw auth (don't know, how cookie login works) and get the "verify your account" prompt. 
After this the next page render the ingress "sign in / learn more" dialog.

verify your account: [click for picture](http://img.gruessung.eu/?f=1475070530.png)
30seconds later: [click for picture](http://img.gruessung.eu/?f=1475070572.png)

I use
`page.render("filepath...");`
for create these screenshots

**Comment by nibogd** [comment]
Hm, it should've detected that something went wrong...
Try to log into your account in browser's Incognito Mode. If it asks to
verify, follow the instructions and ice should work after that.

**Comment by gruessung** [comment]
Mh, i tried Incognito mode several times from different IPs, the message to verify my account does not appear. 
I tried ICE with different accounts, at all the message appear.

**Comment by nibogd** [comment]
Sorry, can't reproduce. I've now tested ice, it failed with 'Something went wrong'. I logged in from incognito and verified my account, works now.

Please try using cookies. It's not so convenient, but i can't suggest anything better. Here is the guide: https://github.com/nibogd/ingress-ice/wiki/Cookies-Authentication.

I will try to find the reason, not sure i will succeed though...

**Comment by nibogd** [comment]
Hm, one thing: PhantomJS is based on QtWebKit, which Google may not like. You could try logging in with another User-Agent string (PhantomJS's one is smth like `Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1`).
