### ISSUE TITLE
IITC plugin with socket.io.js library

### ISSUE THREAD

**Issue by soend** [nibogd/ingress-ice#98]
Hei, im trying to use ingress-ice with custom IITC plugin what uses socket.io. For that it needs to load socket.io.js library. With tampermonkey this is done with `@require  https://path.to.com/socket.io/socket.io.js`. Does anybody have idea how could i load it when using phantomjs?

I have tried adding loading `socket.io.js` into `ice-50-extra.js` where iitc script is loaded without a luck. Also tried to put it in the plugin itself. Every time i get error `TypeError: undefined is not a function (evaluating 'io.connect()`, just like the `socket.io.js` script is not added to the page..

**Comment by nibogd** [comment]
Just add it as an IITC plugin with empty configuration.

**Comment by soend** [comment]
Yes, that was first think i tried. But it seems it wont get loaded properly. Gives me still `TypeError: undefined is not a function (evaluating 'io.connect()'` error.

**Comment by nibogd** [comment]
Oh, sorry. I've just tested websockets, PhantomJS supports them.
After searching, found out that Socket.IO doesn't itself define the `io` variable. In manuals, it is usually loaded with `var io = require("...")`, and if it is undefined, it failed to require Socket.IO.
Does the script require any other libs? Could you send its source?

**Comment by soend** [comment]
No, this plugin only requires socket.io library. Here's simplified version what i was using for testing (socker url is changed):
https://gist.github.com/soend/9e9d7ac96aa43b137c0203eab9ae19ee

**Comment by nibogd** [comment]
Hmm, but io is really not defined. A strange question, but does it work in browser? Don't you need to `require()` socket? I don't know will it work in PJS though...

**Comment by soend** [comment]
Yes, its working in browser using Tampermonkey with @require parameter. require() you need to use on server side to use socket.io.

**Comment by nibogd** [comment]
Then sorry, seems like i can't help. I visited [this Socket.IO demo](http://socket.io/demos/chat/), even there i don't have `io` defined.

**Comment by soend** [comment]
Thanks for looking into this. I got socket.io library recognized by my plugin when using `page.injectJs('/socket.io.js');`.  Very odd..

**Comment by soend** [comment]
I think its time to close this question. My Phantomjs didnt have my domain ssl certificate issuer certificate installed. Bad thing was it wasnt giving any errors anywhere about that also. Anyway running phantomjs with `--ignore-ssl-errors=true` fixed the problem now.

**Comment by nibogd** [comment]
Glad you solved it. Yep, PhantomJS sometimes even doesn't say about syntax errors (neither executes code).
